# DAT210x - Programming with Python for DS

## Module2 - Lab4

Import and alias Pandas:

In [1]:
import pandas as pd

Load up the table from the link, and extract the dataset out of it. If you're having issues with this, look carefully at the sample code provided in the reading:

In [17]:
df = pd.read_html("http://www.espn.com/nhl/statistics/player/_/stat/points/sort/points/year/2015/seasontype/2",header = 1)
len(df) # df is list of dataframes

1

Next up, rename the columns so that they are _similar_ to the column definitions provided to you on the website. Be careful and don't accidentally use any column names twice. If a column uses special characters, you can replace them with regular characters to make it easier to work with:

In [26]:
df[0].columns = ["RK","PLAYER","TEAM","GP","G.1","A.1","PTS","+/-","PIM","PTS/G","SOG","PCT","GWG","G.2","A.2","G.3","A.3"]

Get rid of any row that has at least 4 NANs in it. That is, any rows that do not contain player points statistics:

In [35]:
for x in ["RK","GP","G.1","A.1","PTS","+/-","PIM","PTS/G","SOG","PCT","GWG","G.2","A.2","G.3","A.3"]:
    df[0].loc[:,x] = pd.to_numeric(df[0].loc[:,x],errors = "coerce")
df[0] = df[0].dropna(axis = 0, thresh = 4)

C:\Users\hp\Anaconda3\lib\site-packages\pandas\core\indexing.py:517: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


At this point, look through your dataset by printing it. There probably still are some erroneous rows in there. What indexing command(s) will you use to select all rows EXCEPT those rows?

In [36]:
df[0]

RK                  PLAYER TEAM    GP   G.1   A.1   PTS   +/-   PIM  \
0    1.0          Jamie Benn, LW  DAL  82.0  35.0  52.0  87.0   1.0  64.0   
1    2.0         John Tavares, C  NYI  82.0  38.0  48.0  86.0   5.0  46.0   
2    3.0        Sidney Crosby, C  PIT  77.0  28.0  56.0  84.0   5.0  47.0   
3    4.0       Alex Ovechkin, LW  WSH  81.0  53.0  28.0  81.0  10.0  58.0   
4    NaN       Jakub Voracek, RW  PHI  82.0  22.0  59.0  81.0   1.0  78.0   
5    6.0    Nicklas Backstrom, C  WSH  82.0  18.0  60.0  78.0   5.0  40.0   
6    7.0         Tyler Seguin, C  DAL  71.0  37.0  40.0  77.0  -1.0  20.0   
7    8.0         Jiri Hudler, LW  CGY  78.0  31.0  45.0  76.0  17.0  14.0   
8    NaN        Daniel Sedin, LW  VAN  82.0  20.0  56.0  76.0   5.0  18.0   
9   10.0  Vladimir Tarasenko, RW  STL  77.0  37.0  36.0  73.0  27.0  31.0   
12   NaN        Nick Foligno, LW  CBJ  79.0  31.0  42.0  73.0  16.0  50.0   
13   NaN        Claude Giroux, C  PHI  81.0  25.0  48.0  73.0  -3.0  36.0   
14   NaN         Henrik Sedin, C  VAN  82.0  18.0  55.0  73.0  11.0  22.0   
15  14.0       Steven Stamkos, C   TB  82.0  43.0  29.0  72.0   2.0  49.0   
16   NaN        Tyler Johnson, C   TB  77.0  29.0  43.0  72.0  33.0  24.0   
17  16.0        Ryan Johansen, C  CBJ  82.0  26.0  45.0  71.0  -6.0  40.0   
18  17.0         Joe Pavelski, C   SJ  82.0  37.0  33.0  70.0  12.0  29.0   
19   NaN        Evgeni Malkin, C  PIT  69.0  28.0  42.0  70.0  -2.0  60.0   
20   NaN         Ryan Getzlaf, C  ANA  77.0  25.0  45.0  70.0  15.0  62.0   
21  20.0           Rick Nash, LW  NYR  79.0  42.0  27.0  69.0  29.0  36.0   
24  21.0      Max Pacioretty, LW  MTL  80.0  37.0  30.0  67.0  38.0  32.0   
25   NaN        Logan Couture, C   SJ  82.0  27.0  40.0  67.0  -6.0  12.0   
26  23.0       Jonathan Toews, C  CHI  81.0  28.0  38.0  66.0  30.0  36.0   
27   NaN        Erik Karlsson, D  OTT  82.0  21.0  45.0  66.0   7.0  42.0   
28   NaN   Henrik Zetterberg, LW  DET  77.0  17.0  49.0  66.0  -6.0  32.0   
29  26.0        Pavel Datsyuk, C  DET  63.0  26.0  39.0  65.0  12.0   8.0   
30   NaN         Joe Thornton, C   SJ  78.0  16.0  49.0  65.0  -4.0  30.0   
31  28.0     Nikita Kucherov, RW   TB  82.0  28.0  36.0  64.0  38.0  37.0   
32   NaN        Patrick Kane, RW  CHI  61.0  27.0  37.0  64.0  10.0  10.0   
33   NaN          Mark Stone, RW  OTT  80.0  26.0  38.0  64.0  21.0  14.0   
36   NaN     Alexander Steen, LW  STL  74.0  24.0  40.0  64.0   8.0  33.0   
37   NaN          Kyle Turris, C  OTT  82.0  24.0  40.0  64.0   5.0  36.0   
38   NaN     Johnny Gaudreau, LW  CGY  80.0  24.0  40.0  64.0  11.0  14.0   
39   NaN         Anze Kopitar, C   LA  79.0  16.0  48.0  64.0  -2.0  10.0   
40  35.0        Radim Vrbata, RW  VAN  79.0  31.0  32.0  63.0   6.0  20.0   
41   NaN      Jaden Schwartz, LW  STL  75.0  28.0  35.0  63.0  13.0  16.0   
42   NaN      Filip Forsberg, LW  NSH  82.0  26.0  37.0  63.0  15.0  24.0   
43   NaN       Jordan Eberle, RW  EDM  81.0  24.0  39.0  63.0 -16.0  24.0   
44   NaN        Ondrej Palat, LW   TB  75.0  16.0  47.0  63.0  31.0  24.0   
45  40.0         Zach Parise, LW  MIN  74.0  33.0  29.0  62.0  21.0  41.0   

    PTS/G    SOG   PCT   GWG   G.2   A.2  G.3  A.3  
0    1.06  253.0  13.8   6.0  10.0  13.0  2.0  3.0  
1    1.05  278.0  13.7   8.0  13.0  18.0  0.0  1.0  
2    1.09  237.0  11.8   3.0  10.0  21.0  0.0  0.0  
3    1.00  395.0  13.4  11.0  25.0   9.0  0.0  0.0  
4    0.99  221.0  10.0   3.0  11.0  22.0  0.0  0.0  
5    0.95  153.0  11.8   3.0   3.0  30.0  0.0  0.0  
6    1.08  280.0  13.2   5.0  13.0  16.0  0.0  0.0  
7    0.97  158.0  19.6   5.0   6.0  10.0  0.0  0.0  
8    0.93  226.0   8.9   5.0   4.0  21.0  0.0  0.0  
9    0.95  264.0  14.0   6.0   8.0  10.0  0.0  0.0  
12   0.92  182.0  17.0   3.0  11.0  15.0  0.0  0.0  
13   0.90  279.0   9.0   4.0  14.0  23.0  0.0  0.0  
14   0.89  101.0  17.8   0.0   5.0  20.0  0.0  0.0  
15   0.88  268.0  16.0   6.0  13.0  12.0  0.0  0.0  
16   0.94  203.0  14.3   6.0   8.0   9.0  0.0  0.0  


Get rid of the 'RK' column:

In [40]:
df[0] = df[0].drop(labels = ["RK"], axis = 1)

Make sure there are no holes in your index by resetting it. There is an example of this in the reading material. By the way, drop the original index.

In [41]:
df[0].reset_index(drop  = True, inplace = True)

Check the data type of all columns, and ensure those that should be numeric are numeric.

In [44]:
df[0].dtypes

PLAYER     object
TEAM       object
GP        float64
G.1       float64
A.1       float64
PTS       float64
+/-       float64
PIM       float64
PTS/G     float64
SOG       float64
PCT       float64
GWG       float64
G.2       float64
A.2       float64
G.3       float64
A.3       float64
dtype: object

Your dataframe is now ready! Use the appropriate commands to answer the questions on the course lab page.

In [45]:
df[0].head()

PLAYER TEAM    GP   G.1   A.1   PTS   +/-   PIM  PTS/G    SOG  \
0     Jamie Benn, LW  DAL  82.0  35.0  52.0  87.0   1.0  64.0   1.06  253.0   
1    John Tavares, C  NYI  82.0  38.0  48.0  86.0   5.0  46.0   1.05  278.0   
2   Sidney Crosby, C  PIT  77.0  28.0  56.0  84.0   5.0  47.0   1.09  237.0   
3  Alex Ovechkin, LW  WSH  81.0  53.0  28.0  81.0  10.0  58.0   1.00  395.0   
4  Jakub Voracek, RW  PHI  82.0  22.0  59.0  81.0   1.0  78.0   0.99  221.0   

    PCT   GWG   G.2   A.2  G.3  A.3  
0  13.8   6.0  10.0  13.0  2.0  3.0  
1  13.7   8.0  13.0  18.0  0.0  1.0  
2  11.8   3.0  10.0  21.0  0.0  0.0  
3  13.4  11.0  25.0   9.0  0.0  0.0  
4  10.0   3.0  11.0  22.0  0.0  0.0

In [46]:
df[0].columns

Index(['PLAYER', 'TEAM', 'GP', 'G.1', 'A.1', 'PTS', '+/-', 'PIM', 'PTS/G',
       'SOG', 'PCT', 'GWG', 'G.2', 'A.2', 'G.3', 'A.3'],
      dtype='object')

In [47]:
df[0].describe()

GP        G.1        A.1        PTS        +/-        PIM  \
count  40.000000  40.000000  40.000000  40.000000  40.000000  40.000000   
mean   78.275000  28.050000  41.925000  69.975000  10.350000  32.975000   
std     4.992238   8.123881   8.573625   6.963228  12.986285  16.733948   
min    61.000000  16.000000  27.000000  62.000000 -16.000000   8.000000   
25%    77.000000  24.000000  36.750000  64.000000   1.000000  20.000000   
50%    80.000000  27.000000  40.000000  68.000000   9.000000  32.000000   
75%    82.000000  31.500000  48.000000  73.000000  16.250000  41.250000   
max    82.000000  53.000000  60.000000  87.000000  38.000000  78.000000   

           PTS/G         SOG        PCT        GWG        G.2       A.2  \
count  40.000000   40.000000  40.000000  40.000000  40.000000  40.00000   
mean    0.896250  219.525000  13.015000   4.700000   8.100000  14.60000   
std     0.094535   59.042352   2.619703   2.366432   4.539287   5.82127   
min     0.770000  101.000000   7.200000   0.000000   2.000000   4.00000   
25%     0.817500  182.750000  11.575000   3.000000   5.750000  10.00000   
50%     0.870000  218.000000  13.150000   5.000000   7.000000  14.00000   
75%     0.955000  263.250000  14.425000   6.000000  10.250000  18.00000   
max     1.090000  395.000000  19.600000  11.000000  25.000000  30.00000   

             G.3        A.3  
count  40.000000  40.000000  
mean    0.450000   0.325000  
std     0.959434   0.729858  
min     0.000000   0.000000  
25%     0.000000   0.000000  
50%     0.000000   0.000000  
75%     0.000000   0.000000  
max     4.000000   3.000000

In [48]:
df[0].shape

(40, 16)

In [50]:
len(df[0].loc[:,"PCT"].unique())

36

In [52]:
import numpy as np
np.sum(df[0].loc[[15,16],"GP"])

164.0

In [27]:
   index  month  day  year  session_id
0      0      3   15  2015       17357
1      1      3   16  2015       10011
2      2      3   17  2015       13911
3      4      2   15  2015       13880
4      5      1   15  2015       14023

1
['day']
2
reset_index(drop = True)
3
reset_index()
4
drop_Duplicates
5
drop_duplicates
6
['month']
7
dropDuplicates
8
['month', 'day']
9
drop_index

[[0 1 0 1 0 0 1]
 [1 0 1 0 1 1 1]]


In [28]:
import pandas as pd
df = pd.read_csv('https://goo.gl/ZNqF1j')
print(df.drop_duplicates(subset = ['month', 'day']). reset_index(drop = True) )

   month  day  year  session_id
0      3   15  2015       17357
1      3   16  2015       10011
2      3   17  2015       13911
3      2   15  2015       13880
4      1   15  2015       14023


In [34]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
bank = pd.read_csv('https://goo.gl/npYFvD')
authentic = bank['authentic'].copy()
bank.drop(labels = ['authentic'], inplace = True, axis = 1)
model = RandomForestClassifier( oob_score = True, random_state = 2)
model.fit(bank, authentic)
print(cross_val_score(model, bank, authentic, cv = 3))

[ 0.98908297  0.99343545  0.99343545]


C:\Users\hp\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:453: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:453: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:453: UserWarning: Some inputs do not have OOB scores. This probably means too few tre

In [40]:
import pandas as pd
df = pd.read_csv('https://goo.gl/adrukn')
print(df.P.value_counts().sort_index())

Apples      2
Bananas     2
Cherries    2
Name: P, dtype: int64


In [42]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
df = pd.read_csv('https://goo.gl/MKIGg2')
label = df['class'].copy()
df.drop(labels = 'class', inplace = True, axis = 1)
df_train, df_test, label_train, label_test = train_test_split(df, label,
                                                              test_size = 0.25, 
                                                              random_state = 2)
svc = SVC(C = 0.5)
svc.fit(df_train, label_train)
print(confusion_matrix(label_test, svc.predict(df_test)))

[[25  1]
 [ 0 24]]


In [43]:
import pandas as pd
fifa_wc_venues = pd.read_csv('https://goo.gl/B0mNSo')
print(fifa_wc_venues)

   year          host      continent   winner
0  1998        France         Europe   France
1  2002   South Korea           Asia   Brazil
2  2006       Germany         Europe    Italy
3  2010  South Africa         Africa    Spain
4  2014        Brazil  South America  Germany


In [47]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
wines = pd.read_csv('https://goo.gl/mY06vG', index_col = 0)
labels = wines['quality'].copy()
wines.drop(labels = ['quality'], inplace = True, axis = 1)
parameters = {'C':[1, 3, 5]}
model = SVC()
sv_grid_classifier = GridSearchCV(model, parameters)

sv_grid_classifier.fit(wines, labels)
print(sv_grid_classifier.best_score_)

0.544771446462


In [49]:
import pandas as pd
from sklearn.manifold import Isomap
movies = pd.read_csv('https://goo.gl/J5JtpN')
iso = Isomap(n_neighbors = 5, n_components = 5)
iso.fit(movies)
transformed_samples = iso.transform(movies.iloc[-3:,:])
print(transformed_samples)

[[ 0.04206321 -2.90391578  0.65698039 -3.49211088  4.16032971]
 [ 0.47726725  0.64474638  6.84071941  0.30943502 -0.35196729]
 [ 5.49358453 -0.9699263  -1.8806556  -0.51478669 -3.2115222 ]]


In [51]:
import pandas as pd
df = pd.read_csv('https://goo.gl/qxWClF', na_values = -1)
print(df.fillna(method = 'ffill', limit = 1))

   id store product  cost
0   1     A       X   NaN
1   2     B       X  25.0
2   3     B       Y  25.0
3   4   NaN       Y  15.0
4   5     A     NaN  20.0


In [53]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
df = pd.read_csv('https://goo.gl/VtlArH')
df

x         y   z class
0   4.303220  6.057650   8     A
1   5.248309  4.334538   3     A
2   4.036825  6.217231   5     A
3   6.390432  8.633748  16     B
4   5.574363  2.877591   7     A
5   6.370602  6.052630  19     B
6   6.634470  8.531312  20     B
7   6.800098  8.207374  15     B
8   6.071703  6.055577   4     A
9   7.558412  7.092385  18     B
10  7.337115  8.244454  12     B
11  4.739934  4.872423   1     A
12  9.365486  6.367729  14     B
13  3.767166  3.683694   9     A
14  7.048370  6.472800  11     B
15  5.429528  4.396928   6     A
16  5.386994  3.775082  10     A
17  7.326446  4.440115   2     A
18  6.908938  7.790194  17     B
19  7.501710  7.631036  13     B

In [55]:
target = df['class'].copy()
df.drop(labels = ['class'], inplace = True, axis = 1)
knn = KNeighborsClassifier(n_neighbors = 5)
print(knn.fit(df, target))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')
